Repository BirkhoffG/ReLax, pull requests merged in 2022-12, with the labels that each got.

#72 Support aux arguments of `pred_fn` to be passed to `generate_cf_explanations`
  cfnet/_modidx.py
  cfnet/evaluate.py
  nbs/06_evaluate.ipynb
  nbs/ipynb_path.py
  nbs/sidebar.yml
Labels: enhancement

#75 Refactored TabularDataModule
  cfnet/_modidx.py
  cfnet/data/__init__.py
  cfnet/data/loader.py
  cfnet/data/module.py
  nbs/01_data.loader.ipynb
  nbs/01_data.module.ipynb
  nbs/01_datasets.ipynb
  nbs/sidebar.yml
Labels: enhancement

#76 Document data.module
  cfnet/_modidx.py
  cfnet/data/loader.py
  cfnet/data/module.py
  cfnet/import_essentials.py
  cfnet/utils.py
  nbs/00_utils.ipynb
  nbs/01_data.loader.ipynb
  nbs/01_data.module.ipynb
Labels: documentation

#78 Major refactor for compatibility of `cfnet.data.TabularDataModule`
  cfnet/_modidx.py
  cfnet/data/module.py
  cfnet/datasets.py
  cfnet/evaluate.py
  cfnet/methods/base.py
  cfnet/methods/counternet.py
  cfnet/methods/diverse.py
  cfnet/methods/proto.py
  cfnet/methods/vanilla.py
  cfnet/module.py
  nbs/01_data.module.ipynb
  nbs/01_datasets.ipynb
  nbs/03_training_module.ipynb
  nbs/04_learning.ipynb
  nbs/05_methods.base.ipynb
  nbs/05a_methods.vanilla.ipynb
  nbs/05b_methods.diverse.ipynb
  nbs/05c_methods.prototype.ipynb
  nbs/05d_methods.counternet.ipynb
  nbs/06_evaluate.ipynb
  nbs/images/CounterNet-architecture.svg
  nbs/index.ipynb
  nbs/tutorials/how_to_use_cfnet.ipynb
Labels: enhancement, breaking-changes

#77 Add Visualization
  cfnet/_modidx.py
  cfnet/plots.py
  nbs/07_plotting.ipynb
  nbs/sidebar.yml
  settings.ini
Labels: enhancement
