Repository BirkhoffG/ReLax, pull requests merged in 2023-02, with the labels that each got.

#104 Fix bugs in taking wrong positional default value in `TrainingConfigs`
  nbs/04_learning.ipynb
  relax/trainer.py
Labels: bug

#106 Validate input arguments in `validate_configs`
  nbs/00_utils.ipynb
  relax/utils.py
Labels: bug

#117 Fix typos in docs
  nbs/index.ipynb
  nbs/sidebar.yml
  nbs/tutorials/getting_started.ipynb
Labels: documentation

#119 Improve documentation site
  nbs/00_docs.ipynb
  nbs/01_data.module.ipynb
  nbs/03_training_module.ipynb
  nbs/04_learning.ipynb
  nbs/05d_methods.counternet.ipynb
  nbs/sidebar.yml
  nbs/styles.css
  nbs/theme.scss
  relax/_modidx.py
  relax/data/module.py
  relax/docs.py
  relax/methods/counternet.py
  relax/module.py
  relax/trainer.py
  settings.ini
Labels: documentation, enhancement

#120 Fixed the tutorial link
  README.md
  nbs/index.ipynb
Labels: bug

#121 Fix scss bug
  nbs/theme.scss
Labels: bug
