Repository BirkhoffG/ReLax, pull requests merged in 2023-01, with the labels that each got.

#92 Migrate cfnet to ReLax
  README.md
  nbs/01_data.module.ipynb
  nbs/04_learning.ipynb
  nbs/05b_methods.diverse.ipynb
  nbs/_quarto.yml
  nbs/index.ipynb
  nbs/nbdev.yml
  nbs/tutorials/contribution.ipynb
  nbs/tutorials/install.ipynb
  relax/_modidx.py
  relax/data/module.py
  relax/trainer.py
  settings.ini
Labels: breaking-changes

#96 better `binary_cross_entropy`; replace sigmoid
  nbs/00_utils.ipynb
  nbs/03_training_module.ipynb
  nbs/05a_methods.vanilla.ipynb
  nbs/05c_methods.prototype.ipynb
  nbs/05d_methods.counternet.ipynb
  relax/methods/counternet.py
  relax/methods/proto.py
  relax/methods/vanilla.py
  relax/module.py
  relax/utils.py
Labels: enhancement

#93 Fix bugs in `PredictiveTrainingModule` when using `PredictiveTrainingModuleConfigs` for config
  nbs/00_utils.ipynb
  nbs/01_data.loader.ipynb
  nbs/03_training_module.ipynb
  nbs/tutorials/getting_started.ipynb
  relax/_modidx.py
  relax/module.py
  relax/utils.py
Labels: bug

#97 clean deprecated
  nbs/00_utils.ipynb
  nbs/04b_ckpt_manager.ipynb
  nbs/05_methods.base.ipynb
  nbs/05c_methods.prototype.ipynb
  nbs/06_evaluate.ipynb
  nbs/07_plotting.ipynb
  relax/_ckpt_manager.py
  relax/_modidx.py
  relax/evaluate.py
  relax/methods/base.py
  relax/methods/proto.py
  relax/utils.py
Labels: enhancement, breaking-changes

#99 Remove commented out codes.
  nbs/01_data.loader.ipynb
  nbs/04b_ckpt_manager.ipynb
  nbs/05a_methods.vanilla.ipynb
  nbs/05b_methods.diverse.ipynb
  nbs/05c_methods.prototype.ipynb
  nbs/07_plotting.ipynb
  nbs/tutorials/contribution.ipynb
  relax/_ckpt_manager.py
  relax/methods/diverse.py
  relax/methods/proto.py
  relax/methods/vanilla.py
  relax/plots.py
Labels: misc

#101 Reorgnaize the getting started tutorial
  nbs/_quarto.yml
  nbs/theme.scss
  nbs/tutorials/getting_started.ipynb
Labels: documentation
